version: '3.4'

networks:
  app-network:
    driver: bridge

services:
  hubmeteorologico.api:
    image: ${DOCKER_REGISTRY-}hubmeteorologicoapi
    build:
      context: .
      dockerfile: HubMeteorologico/Dockerfile
    networks:
      - app-network

  db:
    image: postgis/postgis:16-3.4
    container_name: hubmeteorologico-postgres
    environment:
      POSTGRES_PASSWORD: "65876Df&"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "HubMeteorologico"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
  
  redis:
    image: redis:7-alpine
    container_name: hubmeteorologico-redis
    ports:
      - "6379:6379"
    networks:
      - app-network    

volumes:
  db-data:
    